// Defines the witness functions used by the contract.
// No witnesses are required for this contract.
export type Witnesses<PS> = {
}

// Defines circuits that can modify the contract state.
export type ImpureCircuits<PS> = {
  // Stores a new message in the ledger.
  storeMessage(context: __compactRuntime.CircuitContext<PS>,
               newMessage_0: string): __compactRuntime.CircuitResults<PS, []>;
}

// Defines circuits that can be proven/executed.
export type ProvableCircuits<PS> = {
  // Stores a new message in the ledger.
  storeMessage(context: __compactRuntime.CircuitContext<PS>,
               newMessage_0: string): __compactRuntime.CircuitResults<PS, []>;
}

// Defines pure circuits that do not modify state.
// No pure circuits are present.
export type PureCircuits = {
}

// Combines all available contract circuits.
export type Circuits<PS> = {
  // Stores the provided message in the contract state.
  storeMessage(context: __compactRuntime.CircuitContext<PS>,
               newMessage_0: string): __compactRuntime.CircuitResults<PS, []>;
}

// Represents the contract's ledger state.
export type Ledger = {
  // The message currently stored in the ledger.
  readonly message: string;
}

// Contains locations/references to the compiled contract.
export type ContractReferenceLocations = any;

// Contract reference locations generated by the compiler.
export declare const contractReferenceLocations : ContractReferenceLocations;

// Main contract class.
export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  // Witness functions used by the contract.
  witnesses: W;

  // All contract circuits.
  circuits: Circuits<PS>;

  // Circuits that may modify state.
  impureCircuits: ImpureCircuits<PS>;

  // Circuits that can be proven.
  provableCircuits: ProvableCircuits<PS>;

  // Creates a new contract instance with the provided witnesses.
  constructor(witnesses: W);

  // Initializes the contract's state.
  initialState(context: __compactRuntime.ConstructorContext<PS>): __compactRuntime.ConstructorResult<PS>;
}

// Reads and returns the ledger state from the contract state value.
export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;

// Collection of pure circuits available in the contract.
export declare const pureCircuits: PureCircuits;
